# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11f99c237450384b8c9168b316a33ab974ca92ecba1509701633346e768f80353be41e9bc5d9024a68f35a95d4309cb9ab477e39c9394e9ee483f7055a46f572

test:
  secret_key_base: ea9a61c12b83f08c366353b0325c71c9d15a7f72aaa580df0b43ddfa6e720ad85423e8544b896bf6f555d440a9f4d357c02d0da5103ad00046ba7fe59ce8edab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
